services:
  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=java_shareit
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=123456
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  db-init:
    image: postgres:16.1
    container_name: db-init
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql