CREATE TABLE IF NOT EXISTS users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(255) NOT NULL,
            email VARCHAR(512) NOT NULL,
            CONSTRAINT pk_user PRIMARY KEY (id),
            CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

 CREATE TABLE IF NOT EXISTS items (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id BIGINT NOT NULL,
          name VARCHAR(300) NOT NULL,
          description VARCHAR(2000),
          available BOOLEAN NOT NULL,
          CONSTRAINT fk_items_to_users FOREIGN KEY(user_id) REFERENCES users(id)
        );


CREATE TABLE IF NOT EXISTS booking (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          start_from TIMESTAMP WITHOUT TIME ZONE NOT NULL,
          end_to TIMESTAMP WITHOUT TIME ZONE NOT NULL,
          item_id BIGINT NOT NULL,
          status VARCHAR(100) NOT NULL,
          booker_id BIGINT NOT NULL,
          CONSTRAINT fk_booking_to_item FOREIGN KEY(item_id) REFERENCES items(id),
          CONSTRAINT fk_booking_to_user FOREIGN KEY(booker_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        text VARCHAR(2000) NOT NULL,
        item_id BIGINT NOT NULL,
        user_id BIGINT NOT NULL,
        created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        CONSTRAINT fk_comment_to_item FOREIGN KEY(item_id) REFERENCES items(id),
        CONSTRAINT fk_comment_to_user FOREIGN KEY(user_id) REFERENCES users(id)
);